modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/better-respawn"
displayURL="https://modrepo.de/minecraft/better_respawn"
#logoFile="icon.png"
# credits=""
authors="Max Henkel"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/better_respawn.json"
description='''This mod adds a mechanic that lets you respawn near your death location'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"