modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/better-respawn"
[[mods]]
modId = "better_respawn"
version = "${mod_version}"
displayName = "Better Respawn"
updateJSONURL = "https://update.maxhenkel.de/neoforge/better_respawn"
displayURL = "https://modrepo.de/minecraft/better_respawn"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''This mod adds a mechanic that lets you respawn near your death location'''
[[dependencies.better_respawn]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.better_respawn]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"